// Generated by CoffeeScript 1.8.0
var R, im, initialize, k, n, show, showScene, showSlide, v, watch, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

$(function() {
  initialize();
  return watch();
});

R = {};

R.imageSrc = ["images/1.jpg", "images/2.jpg", "images/3.jpg", "images/4.jpg"];

R.names = ['A', 'B', 'C', 'D'];

R.overlays = {};

R.overlays['+'] = 'images/markers/cross.png';

R.overlays['.'] = 'images/markers/dot.png';

R.images = {};

R.images['S'] = "images/S.jpg";

_ref = R.names;
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  n = _ref[_i];
  R.images[n] = '';
}

_ref1 = R.overlays;
for (k in _ref1) {
  v = _ref1[k];
  im = new Image();
  im.src = v;
}

_ref2 = R.images;
for (k in _ref2) {
  v = _ref2[k];
  im = new Image();
  im.src = v;
}

_ref3 = R.imageSrc;
for (_j = 0, _len1 = _ref3.length; _j < _len1; _j++) {
  v = _ref3[_j];
  im = new Image();
  im.src = v;
}

initialize = function() {
  var i, _k, _len2, _ref4, _results;
  if (localStorage.init) {
    console.log('I recognize you. You\'ve been here before!');
    R.names = localStorage.names.split(',');
  } else {
    R.names.sort(function() {
      return 0.5 - Math.random();
    });
    localStorage.names = R.names;
    localStorage.init = true;
  }
  _ref4 = R.names;
  _results = [];
  for (i = _k = 0, _len2 = _ref4.length; _k < _len2; i = ++_k) {
    n = _ref4[i];
    _results.push(R.images[n] = R.imageSrc[i]);
  }
  return _results;
};

show = function(overlay, image) {
  if (overlay == null) {
    overlay = '';
  }
  if (image == null) {
    image = false;
  }
  if (overlay === '.') {
    R.clickable = true;
  } else {
    R.clickable = false;
  }
  if (__indexOf.call(Object.keys(R.images), image) >= 0) {
    $('.image').css('background-image', 'url(' + R.images[image] + ')');
  } else {
    $('.image').css('background-image', 'none');
  }
  if (__indexOf.call(Object.keys(R.overlays), overlay) >= 0) {
    $('.overlay').css('background-image', 'url(' + R.overlays[overlay] + ')').html('');
  } else {
    $('.overlay').css('background-image', 'none').html(overlay);
  }
  return R.slideTime = Date.now();
};

R.slides = [
  {
    o: ' ',
    i: 'A'
  }, {
    o: '.',
    i: 'B'
  }, {
    o: ' ',
    i: 'C'
  }, {
    o: '.',
    i: 'D'
  }, {
    o: '+',
    i: 'N'
  }
];

showSlide = function(slide) {
  return show(slide.o, slide.i);
};

R.scenes = [
  [R.slides[0], R.slides[1], R.slides[2]], [
    {
      o: '+',
      i: ''
    }, {
      o: '',
      i: 'A'
    }, {
      o: '+',
      i: 'B'
    }, {
      o: '',
      i: 'S'
    }
  ]
];

showScene = function(scene, T, callback) {
  var l;
  if (callback == null) {
    callback = (function() {
      return false;
    });
  }
  l = function(i) {
    if (i == null) {
      i = 0;
    }
    showSlide(scene[i]);
    if (i + 1 < scene.length) {
      return setTimeout((function() {
        return l(i + 1);
      }), T);
    } else {
      return callback();
    }
  };
  return l();
};

R.clickable = false;

R.slideTime = Date.now();

watch = function() {
  return $('.image').click(function() {
    return console.log(Date.now() - R.slideTime + ":" + R.clickable);
  });
};
